export const homeObjOne = {
	id: "about",
	lightBg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: "A za darmo?",
	headLine: "No pewnie!",
	
	imgStart: false,
	img: require("../images/svg-1.svg").default,
	alt: "SuccessImg",
	dark: true,
	primary: true,
	darkText: false,
};
export const homeObjTwo = {
	id: "discover",
	lightBg: true,
	lightText: false,
	lightTextDesc: true,
	topLine: "Można stworzyć listę pracowników w dowolnym programie do edycji tekstu...",
	headLine: "...więc dlaczego warto korzystać z Fasttasking?",
	describtion:
		"Dzięki fasttasking masz dostęp do wszystkich informacji na temat pracowników prowadzących zajęcia oraz liderów zespołów!",
	imgStart: true,
	img: require("../images/svg-3.svg").default,
	alt: "SuccessImg",
	dark: false,
	primary: false,
	darkText: true,
};
export const homeObjThree = {
	id: "signup",
	lightBg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: "Wypróbuj Fasttasking",
	headLine: "Dzięki tej aplikacji będziesz miał wgląd do wielu danych ",
	imgStart: false,
	img: require("../images/svg-2.svg").default,
	alt: "SuccessImg",
	dark: false,
	primary: true,
	darkText: false,
};
